# Generated by Django 5.2.11 on 2026-03-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='is_followed_p',
            new_name='is_followed',
        ),
    ]
