# Generated by Django 5.2.11 on 2026-03-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_feed_like_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_email', models.EmailField(default='', max_length=254)),
                ('following_email', models.EmailField(default='', max_length=254)),
                ('is_followed', models.BooleanField(default=True)),
            ],
        ),
    ]
