# Generated by Django 5.2.11 on 2026-03-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('feed_id', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_email', 'following_email')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('feed_id', 'email')},
        ),
    ]
